### PR TITLE
add timer when sending tr

### PR DESCRIPTION
**Pull request by ttaoS**

### CODE REVIEW

**Comment by ttaoS** [comment]
this pr is to add timer so page will be redirected to home page after 10 sec if the tr final status still hasn't been received yet.

**Comment by hskang9** [comment]
lgtm

**Comment by anjj123** [comment]
10 seconds sounds a bit too long. Whats the average expected time for a tx to send? Add only a few seconds to that estimate imo

**Comment by ttaoS** [comment]
> Will setTimeout be more straightforward than setInterval?

yeah. i think we can use setTimeout instead

**Comment by ttaoS** [comment]
> 10 seconds sounds a bit too long. Whats the average expected time for a tx to send? Add only a few seconds to that estimate imo

updated to 6 sec

**Comment by ttaoS** [comment]
> Will setTimeout be more straightforward than setInterval?

changed

**Pull request merged**
